import { Children, useEffect, useState } from "react";
import styles from "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css";
import {
  MainContainer,
  ChatContainer,
  MessageList,
  Message,
  MessageInput,
  Avatar,
} from "@chatscope/chat-ui-kit-react";
import {
  useChat,
  ChatMessage,
  MessageContentType,
  MessageDirection,
  MessageStatus,
  MessageContent,
  TextContent,
  User,
} from "@chatscope/use-chat";

// import { Spinner } from "@nextui-org/spinner";

export const AssistantPanel = ({
  useMT,
  toggleUseMT,
  usePII,
  toggleUsePII,
}) => {
  const [messages, updateMessages] = useState(undefined);
  const [currentMessage, updateCurrentChat] = useState(undefined);
  const [showSpinner, setSpinner] = useState("hidden");

  const fetchAssistantRes = async (message) => {
    var postData = {
      prompt: message,
      useMT: useMT,
      usePII: usePII,
      temperature: 0.8,
      max_new_tokens: 128,
      top_p: 0.8,
      deployment: "phi-3-mini-128k-instruct-2",
    };

    console.log(postData);

    setSpinner("visible");

    try {
      const response = await fetch("/assistant/generateResponse", {
        method: "post",
        headers: {
          "Content-Type": "application/json",
          "x-access-token": "token-value",
        },
        body: JSON.stringify(postData),
      });

      const data = await response.json();
      updateMessages(data.messages);
      console.log(data);
    } catch (error) {
      console.error("Error:", error);
    }

    setSpinner("hidden");
  };

  const toggleMT = () => {
    toggleUseMT(!useMT);
    localStorage.setItem("useMT", useMT);
    console.log(localStorage.getItem("useMT"));
  };

  const togglePII = () => {
    toggleUsePII(!usePII);
    localStorage.setItem("usePII", usePII);
    console.log(localStorage.getItem("usePII"));
  };

  const handleChange = (value) => {
    //enable spinner
    if (value !== currentMessage) updateCurrentChat(value);
  };

  const handleSend = () => {
    const query = new ChatMessage({
      id: "", // Id will be generated by storage generator, so here you can pass an empty string
      content: currentMessage,
      contentType: MessageContentType.TextHtml,
      senderId: "user-123",
      direction: MessageDirection.Outgoing,
      status: MessageStatus.Sent,
    });

    console.log(currentMessage);

    fetchAssistantRes(query);
    updateCurrentChat("");

    // send the req
  };
  useEffect(() => {
    //    fetchData();
  }, []);

  return (
    <div>
      <div
        dir="ltr"
        style={{
          position: "relative",
          height: "870px",
          textAlign: "left",
          fontFamily: "Segoe UI",
          lineHeight: "1.5",
        }}
      >
        <MainContainer>
          <ChatContainer>
            <MessageList>
              {messages ? (
                messages.map((message) => (
                  <div>
                    <Message
                      key={message.id}
                      model={{
                        message: message.content,
                        id: message.id,
                        direction: message.direction,
                        sentTime: "just now",
                        position: "normal",
                      }}
                    />
                  </div>
                ))
              ) : (
                <div style={{ visibility: "hidden" }}></div>
              )}
              <div
                class="circle"
                id="spinnerID"
                style={{ visibility: showSpinner }}
              ></div>
              <div
                style={{
                  fontSize: 12,
                  textAlign: "center",
                  visibility: showSpinner,
                }}
              >
                Generating response
              </div>
            </MessageList>
          </ChatContainer>
        </MainContainer>
        <MessageInput
          style={{
            height: "60px",
            width: "80%",
            marginLeft: "0",
            marginTop: "5px",
          }}
          value={currentMessage}
          onChange={handleChange}
          onSend={() => handleSend()}
          attachButton={false}
          placeholder="Ask anything (Shift + Enter for new line)"
        />
      </div>
      <label class="switch1">
        <input type="checkbox" onChange={toggleMT} checked={useMT} />
        <div class="slider round"></div>
      </label>
    </div>
  );
};
